apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-go
  name: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - image: localhost/hello-go:latest
        name: hello-go
        imagePullPolicy: Never
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-go
  name: hello-go
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-go
  type: ClusterIP
